# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import propagation_pb2 as propagation__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in propagation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PropagationServiceStub(object):
    """Main service for change propagation and Kilo Agent integration
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessChange = channel.unary_unary(
                '/propagation.PropagationService/ProcessChange',
                request_serializer=propagation__pb2.ChangeRequest.SerializeToString,
                response_deserializer=propagation__pb2.ChangeResponse.FromString,
                _registered_method=True)
        self.EvaluateImpact = channel.unary_unary(
                '/propagation.PropagationService/EvaluateImpact',
                request_serializer=propagation__pb2.ImpactRequest.SerializeToString,
                response_deserializer=propagation__pb2.ImpactResponse.FromString,
                _registered_method=True)
        self.GetSuggestions = channel.unary_stream(
                '/propagation.PropagationService/GetSuggestions',
                request_serializer=propagation__pb2.SuggestionRequest.SerializeToString,
                response_deserializer=propagation__pb2.SuggestionResponse.FromString,
                _registered_method=True)
        self.ApplySuggestion = channel.unary_unary(
                '/propagation.PropagationService/ApplySuggestion',
                request_serializer=propagation__pb2.ApplyRequest.SerializeToString,
                response_deserializer=propagation__pb2.ApplyResponse.FromString,
                _registered_method=True)
        self.RejectSuggestion = channel.unary_unary(
                '/propagation.PropagationService/RejectSuggestion',
                request_serializer=propagation__pb2.RejectRequest.SerializeToString,
                response_deserializer=propagation__pb2.RejectResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/propagation.PropagationService/HealthCheck',
                request_serializer=propagation__pb2.HealthRequest.SerializeToString,
                response_deserializer=propagation__pb2.HealthResponse.FromString,
                _registered_method=True)


class PropagationServiceServicer(object):
    """Main service for change propagation and Kilo Agent integration
    """

    def ProcessChange(self, request, context):
        """Process a change and find affected nodes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EvaluateImpact(self, request, context):
        """Evaluate impact on linked nodes without applying
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSuggestions(self, request, context):
        """Stream AI-generated suggestions for affected nodes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApplySuggestion(self, request, context):
        """Apply an approved suggestion
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RejectSuggestion(self, request, context):
        """Reject a suggestion
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PropagationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessChange': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessChange,
                    request_deserializer=propagation__pb2.ChangeRequest.FromString,
                    response_serializer=propagation__pb2.ChangeResponse.SerializeToString,
            ),
            'EvaluateImpact': grpc.unary_unary_rpc_method_handler(
                    servicer.EvaluateImpact,
                    request_deserializer=propagation__pb2.ImpactRequest.FromString,
                    response_serializer=propagation__pb2.ImpactResponse.SerializeToString,
            ),
            'GetSuggestions': grpc.unary_stream_rpc_method_handler(
                    servicer.GetSuggestions,
                    request_deserializer=propagation__pb2.SuggestionRequest.FromString,
                    response_serializer=propagation__pb2.SuggestionResponse.SerializeToString,
            ),
            'ApplySuggestion': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplySuggestion,
                    request_deserializer=propagation__pb2.ApplyRequest.FromString,
                    response_serializer=propagation__pb2.ApplyResponse.SerializeToString,
            ),
            'RejectSuggestion': grpc.unary_unary_rpc_method_handler(
                    servicer.RejectSuggestion,
                    request_deserializer=propagation__pb2.RejectRequest.FromString,
                    response_serializer=propagation__pb2.RejectResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=propagation__pb2.HealthRequest.FromString,
                    response_serializer=propagation__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'propagation.PropagationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('propagation.PropagationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PropagationService(object):
    """Main service for change propagation and Kilo Agent integration
    """

    @staticmethod
    def ProcessChange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/propagation.PropagationService/ProcessChange',
            propagation__pb2.ChangeRequest.SerializeToString,
            propagation__pb2.ChangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EvaluateImpact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/propagation.PropagationService/EvaluateImpact',
            propagation__pb2.ImpactRequest.SerializeToString,
            propagation__pb2.ImpactResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSuggestions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/propagation.PropagationService/GetSuggestions',
            propagation__pb2.SuggestionRequest.SerializeToString,
            propagation__pb2.SuggestionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApplySuggestion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/propagation.PropagationService/ApplySuggestion',
            propagation__pb2.ApplyRequest.SerializeToString,
            propagation__pb2.ApplyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RejectSuggestion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/propagation.PropagationService/RejectSuggestion',
            propagation__pb2.RejectRequest.SerializeToString,
            propagation__pb2.RejectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/propagation.PropagationService/HealthCheck',
            propagation__pb2.HealthRequest.SerializeToString,
            propagation__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
