%%{ init : { "theme" : "default" } }%%
C4Context
    title Speichereffizienz System Architecture

    Person(customer, "Kunde", "Ein Benutzer, der das System verwendet.")
    System(system, "Speichereffizienz System", "Ein System, das speichereffizient arbeitet.")

    Rel(customer, system, "Verwendet")