"""Test data factories for all entities.

Auto-generated by requirements_engineer pipeline.
Uses factory_boy for declarative test data.
"""
import factory
from uuid import uuid4
from datetime import datetime


class UserFactory(factory.Factory):
    """Factory for user entity."""

    class Meta:
        model = dict  # Replace with ORM model

    user_id = factory.LazyFunction(uuid4)
    phone_number = factory.Faker('phone_number')
    phone_verified_at = factory.Faker('date_time')
    status = factory.Faker('random_element', elements=['active', 'disabled', 'pending_verification'])
    created_at = factory.Faker('date_time')
    updated_at = factory.Faker('date_time')


class UserProfileFactory(factory.Factory):
    """Factory for user_profile entity."""

    class Meta:
        model = dict  # Replace with ORM model

    profile_id = factory.LazyFunction(uuid4)
    user_id = factory.SubFactory(UserFactory)
    display_name = factory.Faker('name')
    status_text = factory.Faker('text', max_nb_chars=50)
    profile_image_url = factory.Faker('text', max_nb_chars=50)
    show_phone_number = factory.Faker('boolean')
    qr_code_value = factory.Faker('text', max_nb_chars=50)
    qr_code_generated_at = factory.Faker('date_time')
    created_at = factory.Faker('date_time')
    updated_at = factory.Faker('date_time')


class UserDeviceFactory(factory.Factory):
    """Factory for user_device entity."""

    class Meta:
        model = dict  # Replace with ORM model

    device_id = factory.LazyFunction(uuid4)
    user_id = factory.SubFactory(UserFactory)
    device_name = factory.Faker('text', max_nb_chars=50)
    device_platform = factory.Faker('random_element', elements=['ios', 'android', 'web', 'desktop', 'other'])
    last_active_at = factory.Faker('date_time')
    created_at = factory.Faker('date_time')
    updated_at = factory.Faker('date_time')


class AuthCredentialFactory(factory.Factory):
    """Factory for auth_credential entity."""

    class Meta:
        model = dict  # Replace with ORM model

    credential_id = factory.LazyFunction(uuid4)
    user_id = factory.SubFactory(UserFactory)
    credential_type = factory.Faker('random_element', elements=['pin_2fa', 'biometric', 'passkey'])
    credential_data = factory.Faker('paragraph')
    is_enabled = factory.Faker('boolean')
    created_at = factory.Faker('date_time')
    updated_at = factory.Faker('date_time')


class ChatFactory(factory.Factory):
    """Factory for chat entity."""

    class Meta:
        model = dict  # Replace with ORM model

    chat_id = factory.LazyFunction(uuid4)
    chat_name = factory.Faker('text', max_nb_chars=50)
    is_locked = factory.Faker('boolean')
    lock_method = factory.Faker('random_element', elements=['pin', 'biometric', 'password', 'none'])
    created_at = factory.Faker('date_time')
    updated_at = factory.Faker('date_time')


class MessageFactory(factory.Factory):
    """Factory for message entity."""

    class Meta:
        model = dict  # Replace with ORM model

    message_id = factory.LazyFunction(uuid4)
    chat_id = factory.SubFactory(ChatFactory)
    sender_user_id = factory.Faker('text', max_nb_chars=50)
    message_type = factory.Faker('random_element', elements=['text', 'voice', 'media'])
    content_text = factory.Faker('paragraph')
    parent_message_id = factory.SubFactory(MessageFactory)
    is_forwarded = factory.Faker('boolean')
    is_deleted = factory.Faker('boolean')
    is_edited = factory.Faker('boolean')
    edited_at = factory.Faker('date_time')
    expires_at = factory.Faker('date_time')
    created_at = factory.Faker('date_time')
    updated_at = factory.Faker('date_time')


class MessageMediaFactory(factory.Factory):
    """Factory for message_media entity."""

    class Meta:
        model = dict  # Replace with ORM model

    media_id = factory.LazyFunction(uuid4)
    message_id = factory.SubFactory(MessageFactory)
    media_type = factory.Faker('random_element', elements=['voice', 'image', 'video', 'file'])
    media_url = factory.Faker('text', max_nb_chars=50)
    is_view_once = factory.Faker('boolean')
    created_at = factory.Faker('date_time')
    updated_at = factory.Faker('date_time')


class MessageReactionFactory(factory.Factory):
    """Factory for message_reaction entity."""

    class Meta:
        model = dict  # Replace with ORM model

    reaction_id = factory.LazyFunction(uuid4)
    message_id = factory.SubFactory(MessageFactory)
    reacting_user_id = factory.Faker('text', max_nb_chars=50)
    emoji = factory.Faker('text', max_nb_chars=50)
    created_at = factory.Faker('date_time')
    updated_at = factory.Faker('date_time')


class GroupChatFactory(factory.Factory):
    """Factory for group_chat entity."""

    class Meta:
        model = dict  # Replace with ORM model

    group_chat_id = factory.LazyFunction(uuid4)
    group_name = factory.Faker('text', max_nb_chars=50)
    group_description = factory.Faker('paragraph')
    invite_link_url = factory.Faker('text', max_nb_chars=50)
    invite_link_enabled = factory.Faker('boolean')
    setting_admin_only_posting = factory.Faker('boolean')
    setting_allow_member_invite = factory.Faker('boolean')
    created_at = factory.Faker('date_time')
    updated_at = factory.Faker('date_time')


class GroupMemberFactory(factory.Factory):
    """Factory for group_member entity."""

    class Meta:
        model = dict  # Replace with ORM model

    group_member_id = factory.LazyFunction(uuid4)
    group_chat_id = factory.SubFactory(GroupChatFactory)
    user_id = factory.SubFactory(UserFactory)
    role = factory.Faker('random_element', elements=['admin', 'member'])
    left_silently = factory.Faker('boolean')
    left_at = factory.Faker('date_time')
    created_at = factory.Faker('date_time')
    updated_at = factory.Faker('date_time')


class MessageMentionFactory(factory.Factory):
    """Factory for message_mention entity."""

    class Meta:
        model = dict  # Replace with ORM model

    mention_id = factory.LazyFunction(uuid4)
    message_id = factory.SubFactory(MessageFactory)
    mentioned_user_id = factory.SubFactory(UserFactory)
    position_start = factory.Faker('random_int', min=0, max=10000)
    position_end = factory.Faker('random_int', min=0, max=10000)
    created_at = factory.Faker('date_time')
    updated_at = factory.Faker('date_time')


class CommunityFactory(factory.Factory):
    """Factory for Community entity."""

    class Meta:
        model = dict  # Replace with ORM model

    community_id = factory.LazyFunction(uuid4)
    name = factory.Faker('name')
    created_at = factory.Faker('date_time')
    updated_at = factory.Faker('date_time')


class GroupFactory(factory.Factory):
    """Factory for Group entity."""

    class Meta:
        model = dict  # Replace with ORM model

    group_id = factory.LazyFunction(uuid4)
    community_id = factory.SubFactory(CommunityFactory)
    name = factory.Faker('name')
    created_at = factory.Faker('date_time')
    updated_at = factory.Faker('date_time')


class ChannelFactory(factory.Factory):
    """Factory for Channel entity."""

    class Meta:
        model = dict  # Replace with ORM model

    channel_id = factory.LazyFunction(uuid4)
    group_id = factory.SubFactory(GroupFactory)
    name = factory.Faker('name')
    is_one_way_broadcast = factory.Faker('boolean')
    created_at = factory.Faker('date_time')
    updated_at = factory.Faker('date_time')


class PollFactory(factory.Factory):
    """Factory for Poll entity."""

    class Meta:
        model = dict  # Replace with ORM model

    poll_id = factory.LazyFunction(uuid4)
    chat_context_type = factory.Faker('random_element', elements=['group', 'individual'])
    chat_context_id = factory.LazyFunction(uuid4)
    question_text = factory.Faker('paragraph')
    created_at = factory.Faker('date_time')
    updated_at = factory.Faker('date_time')


class CallFactory(factory.Factory):
    """Factory for Call entity."""

    class Meta:
        model = dict  # Replace with ORM model

    call_id = factory.LazyFunction(uuid4)
    call_type = factory.Faker('random_element', elements=['voice', 'video'])
    is_group_call = factory.Faker('boolean')
    is_encrypted = factory.Faker('boolean')
    screen_share_enabled = factory.Faker('boolean')
    scheduled_at = factory.Faker('date_time')
    call_link_url = factory.Faker('text', max_nb_chars=50)
    quick_reject_message = factory.Faker('text', max_nb_chars=50)
    created_at = factory.Faker('date_time')
    updated_at = factory.Faker('date_time')


class ContactFactory(factory.Factory):
    """Factory for contact entity."""

    class Meta:
        model = dict  # Replace with ORM model

    contact_id = factory.LazyFunction(uuid4)
    display_name = factory.Faker('name')
    phone_number = factory.Faker('phone_number')
    status_muted = factory.Faker('boolean')
    created_at = factory.Faker('date_time')
    updated_at = factory.Faker('date_time')


class CallLogFactory(factory.Factory):
    """Factory for call_log entity."""

    class Meta:
        model = dict  # Replace with ORM model

    call_log_id = factory.LazyFunction(uuid4)
    contact_id = factory.SubFactory(ContactFactory)
    started_at = factory.Faker('date_time')
    ended_at = factory.Faker('date_time')
    duration_seconds = factory.Faker('random_int', min=0, max=10000)
    created_at = factory.Faker('date_time')
    updated_at = factory.Faker('date_time')


class StatusUpdateFactory(factory.Factory):
    """Factory for status_update entity."""

    class Meta:
        model = dict  # Replace with ORM model

    status_update_id = factory.LazyFunction(uuid4)
    contact_id = factory.SubFactory(ContactFactory)
    content_text = factory.Faker('paragraph')
    expires_at = factory.Faker('date_time')
    visibility = factory.Faker('random_element', elements=['public', 'contacts_only', 'custom'])
    created_at = factory.Faker('date_time')
    updated_at = factory.Faker('date_time')


class StatusReplyFactory(factory.Factory):
    """Factory for status_reply entity."""

    class Meta:
        model = dict  # Replace with ORM model

    status_reply_id = factory.LazyFunction(uuid4)
    status_update_id = factory.SubFactory(StatusUpdateFactory)
    reply_text = factory.Faker('paragraph')
    created_at = factory.Faker('date_time')
    updated_at = factory.Faker('date_time')


class MediaItemFactory(factory.Factory):
    """Factory for media_item entity."""

    class Meta:
        model = dict  # Replace with ORM model

    media_item_id = factory.LazyFunction(uuid4)
    sender_contact_id = factory.SubFactory(ContactFactory)
    status_update_id = factory.SubFactory(StatusUpdateFactory)
    media_type = factory.Faker('random_element', elements=['image', 'video', 'document'])
    file_name = factory.Faker('text', max_nb_chars=50)
    file_url = factory.Faker('text', max_nb_chars=50)
    size_bytes = factory.Faker('random_int', min=0, max=10000)
    edited_flag = factory.Faker('boolean')
    edit_notes = factory.Faker('paragraph')
    created_at = factory.Faker('date_time')
    updated_at = factory.Faker('date_time')


class MediaAttachmentFactory(factory.Factory):
    """Factory for media_attachment entity."""

    class Meta:
        model = dict  # Replace with ORM model

    attachment_id = factory.LazyFunction(uuid4)
    message_id = factory.SubFactory(MessageFactory)
    media_type = factory.Faker('random_element', elements=['sticker', 'gif', 'audio', 'image', 'video'])
    file_url = factory.Faker('text', max_nb_chars=50)
    source_library = factory.Faker('random_element', elements=['camera', 'gallery', 'external'])
    is_hd = factory.Faker('boolean')
    duration_seconds = factory.Faker('random_int', min=0, max=10000)
    created_at = factory.Faker('date_time')
    updated_at = factory.Faker('date_time')


class EncryptionSessionFactory(factory.Factory):
    """Factory for encryption_session entity."""

    class Meta:
        model = dict  # Replace with ORM model

    encryption_session_id = factory.LazyFunction(uuid4)
    chat_id = factory.LazyFunction(uuid4)
    security_code = factory.Faker('text', max_nb_chars=50)
    verification_status = factory.Faker('random_element', elements=['unverified', 'verified'])
    verified_at = factory.Faker('date_time')
    created_at = factory.Faker('date_time')
    updated_at = factory.Faker('date_time')


class ContactBlockFactory(factory.Factory):
    """Factory for contact_block entity."""

    class Meta:
        model = dict  # Replace with ORM model

    block_id = factory.LazyFunction(uuid4)
    blocker_user_id = factory.SubFactory(UserFactory)
    blocked_user_id = factory.SubFactory(UserFactory)
    created_at = factory.Faker('date_time')
    updated_at = factory.Faker('date_time')


class ReportFactory(factory.Factory):
    """Factory for report entity."""

    class Meta:
        model = dict  # Replace with ORM model

    report_id = factory.LazyFunction(uuid4)
    reporter_user_id = factory.SubFactory(UserFactory)
    target_message_id = factory.SubFactory(MessageFactory)
    target_user_id = factory.SubFactory(UserFactory)
    reason = factory.Faker('paragraph')
    status = factory.Faker('random_element', elements=['open', 'reviewed', 'resolved', 'rejected'])
    created_at = factory.Faker('date_time')
    updated_at = factory.Faker('date_time')


class NotificationSettingFactory(factory.Factory):
    """Factory for notification_setting entity."""

    class Meta:
        model = dict  # Replace with ORM model

    notification_setting_id = factory.LazyFunction(uuid4)
    user_id = factory.SubFactory(UserFactory)
    push_enabled = factory.Faker('boolean')
    preview_enabled = factory.Faker('boolean')
    quick_reply_enabled = factory.Faker('boolean')
    do_not_disturb_enabled = factory.Faker('boolean')
    reaction_notifications_enabled = factory.Faker('boolean')
    call_notification_mode = factory.Faker('random_element', elements=['all', 'missed_only', 'none'])
    created_at = factory.Faker('date_time')
    updated_at = factory.Faker('date_time')


class WhatsappUserFactory(factory.Factory):
    """Factory for whatsapp_user entity."""

    class Meta:
        model = dict  # Replace with ORM model

    user_id = factory.LazyFunction(uuid4)
    phone_number = factory.Faker('phone_number')
    display_name = factory.Faker('name')
    online_status_visibility = factory.Faker('random_element', elements=['public', 'contacts_only', 'nobody'])
    created_at = factory.Faker('date_time')
    updated_at = factory.Faker('date_time')


class LabelFactory(factory.Factory):
    """Factory for label entity."""

    class Meta:
        model = dict  # Replace with ORM model

    label_id = factory.LazyFunction(uuid4)
    owner_user_id = factory.SubFactory(WhatsappUserFactory)
    label_name = factory.Faker('text', max_nb_chars=50)
    color = factory.Faker('hex_color')
    created_at = factory.Faker('date_time')
    updated_at = factory.Faker('date_time')


class UserprivacysettingFactory(factory.Factory):
    """Factory for UserPrivacySetting entity."""

    class Meta:
        model = dict  # Replace with ORM model

    privacy_setting_id = factory.LazyFunction(uuid4)
    user_id = factory.SubFactory(UserFactory)
    read_receipt_enabled = factory.Faker('boolean')
    profile_photo_visibility = factory.Faker('random_element', elements=['everyone', 'contacts', 'nobody'])
    status_text_visibility = factory.Faker('random_element', elements=['everyone', 'contacts', 'nobody'])
    group_invite_permission = factory.Faker('random_element', elements=['everyone', 'contacts', 'nobody'])
    created_at = factory.Faker('date_time')
    updated_at = factory.Faker('date_time')


class UserappearancesettingFactory(factory.Factory):
    """Factory for UserAppearanceSetting entity."""

    class Meta:
        model = dict  # Replace with ORM model

    appearance_setting_id = factory.LazyFunction(uuid4)
    user_id = factory.SubFactory(UserFactory)
    chat_background = factory.Faker('text', max_nb_chars=50)
    dark_mode_enabled = factory.Faker('boolean')
    language_code = factory.Faker('language_code')
    created_at = factory.Faker('date_time')
    updated_at = factory.Faker('date_time')


class UserusagesettingFactory(factory.Factory):
    """Factory for UserUsageSetting entity."""

    class Meta:
        model = dict  # Replace with ORM model

    usage_setting_id = factory.LazyFunction(uuid4)
    user_id = factory.SubFactory(UserFactory)
    storage_used_mb = factory.Faker('pydecimal', left_digits=5, right_digits=2, positive=True)
    storage_limit_mb = factory.Faker('pydecimal', left_digits=5, right_digits=2, positive=True)
    data_usage_control_enabled = factory.Faker('boolean')
    created_at = factory.Faker('date_time')
    updated_at = factory.Faker('date_time')


class UserbackupsettingFactory(factory.Factory):
    """Factory for UserBackupSetting entity."""

    class Meta:
        model = dict  # Replace with ORM model

    backup_setting_id = factory.LazyFunction(uuid4)
    user_id = factory.SubFactory(UserFactory)
    cloud_backup_enabled = factory.Faker('boolean')
    last_backup_at = factory.Faker('date_time')
    created_at = factory.Faker('date_time')
    updated_at = factory.Faker('date_time')


class BackupFactory(factory.Factory):
    """Factory for backup entity."""

    class Meta:
        model = dict  # Replace with ORM model

    backup_id = factory.LazyFunction(uuid4)
    chat_id = factory.SubFactory(ChatFactory)
    is_end_to_end_encrypted = factory.Faker('boolean')
    created_at = factory.Faker('date_time')
    updated_at = factory.Faker('date_time')


class BusinessProfileFactory(factory.Factory):
    """Factory for business_profile entity."""

    class Meta:
        model = dict  # Replace with ORM model

    business_profile_id = factory.LazyFunction(uuid4)
    display_name = factory.Faker('name')
    verification_status = factory.Faker('random_element', elements=['unverified', 'pending', 'verified'])
    created_at = factory.Faker('date_time')
    updated_at = factory.Faker('date_time')


class QuickReplyFactory(factory.Factory):
    """Factory for quick_reply entity."""

    class Meta:
        model = dict  # Replace with ORM model

    quick_reply_id = factory.LazyFunction(uuid4)
    business_profile_id = factory.SubFactory(BusinessProfileFactory)
    shortcut = factory.Faker('text', max_nb_chars=50)
    message_text = factory.Faker('paragraph')
    created_at = factory.Faker('date_time')
    updated_at = factory.Faker('date_time')


class AutoMessageFactory(factory.Factory):
    """Factory for auto_message entity."""

    class Meta:
        model = dict  # Replace with ORM model

    auto_message_id = factory.LazyFunction(uuid4)
    business_profile_id = factory.SubFactory(BusinessProfileFactory)
    message_type = factory.Faker('random_element', elements=['away', 'greeting'])
    message_text = factory.Faker('paragraph')
    is_active = factory.Faker('boolean')
    created_at = factory.Faker('date_time')
    updated_at = factory.Faker('date_time')


class BusinessFactory(factory.Factory):
    """Factory for business entity."""

    class Meta:
        model = dict  # Replace with ORM model

    business_id = factory.LazyFunction(uuid4)
    business_name = factory.Faker('text', max_nb_chars=50)
    api_access_enabled = factory.Faker('boolean')
    created_at = factory.Faker('date_time')
    updated_at = factory.Faker('date_time')


class ProductFactory(factory.Factory):
    """Factory for product entity."""

    class Meta:
        model = dict  # Replace with ORM model

    product_id = factory.LazyFunction(uuid4)
    business_id = factory.SubFactory(BusinessFactory)
    product_name = factory.Faker('text', max_nb_chars=50)
    description = factory.Faker('paragraph')
    price_amount = factory.Faker('pydecimal', left_digits=5, right_digits=2, positive=True)
    currency_code = factory.Faker('text', max_nb_chars=50)
    created_at = factory.Faker('date_time')
    updated_at = factory.Faker('date_time')


class CartFactory(factory.Factory):
    """Factory for cart entity."""

    class Meta:
        model = dict  # Replace with ORM model

    cart_id = factory.LazyFunction(uuid4)
    business_id = factory.SubFactory(BusinessFactory)
    status = factory.Faker('random_element', elements=['open', 'ordered', 'abandoned'])
    total_amount = factory.Faker('pydecimal', left_digits=5, right_digits=2, positive=True)
    currency_code = factory.Faker('text', max_nb_chars=50)
    created_at = factory.Faker('date_time')
    updated_at = factory.Faker('date_time')


class PaymentFactory(factory.Factory):
    """Factory for payment entity."""

    class Meta:
        model = dict  # Replace with ORM model

    payment_id = factory.LazyFunction(uuid4)
    cart_id = factory.SubFactory(CartFactory)
    payment_status = factory.Faker('random_element', elements=['pending', 'completed', 'failed', 'refunded'])
    amount = factory.Faker('pydecimal', left_digits=5, right_digits=2, positive=True)
    currency_code = factory.Faker('text', max_nb_chars=50)
    market_code = factory.Faker('text', max_nb_chars=50)
    created_at = factory.Faker('date_time')
    updated_at = factory.Faker('date_time')


class BusinessStatisticFactory(factory.Factory):
    """Factory for business_statistic entity."""

    class Meta:
        model = dict  # Replace with ORM model

    stat_id = factory.LazyFunction(uuid4)
    business_id = factory.SubFactory(BusinessFactory)
    period_start = factory.Faker('date_object')
    period_end = factory.Faker('date_object')
    messages_sent_count = factory.Faker('random_int', min=0, max=10000)
    messages_received_count = factory.Faker('random_int', min=0, max=10000)
    created_at = factory.Faker('date_time')
    updated_at = factory.Faker('date_time')


class IntegrationFeatureFactory(factory.Factory):
    """Factory for integration_feature entity."""

    class Meta:
        model = dict  # Replace with ORM model

    integration_feature_id = factory.LazyFunction(uuid4)
    feature_type = factory.Faker('random_element', elements=['share_extension', 'voice_assistant', 'widget', 'watch_app', 'desktop_app', 'web_version'])
    requirement_level = factory.Faker('random_element', elements=['must', 'should'])
    description = factory.Faker('paragraph')
    created_at = factory.Faker('date_time')
    updated_at = factory.Faker('date_time')


class PerformanceRequirementFactory(factory.Factory):
    """Factory for performance_requirement entity."""

    class Meta:
        model = dict  # Replace with ORM model

    performance_requirement_id = factory.LazyFunction(uuid4)
    metric_type = factory.Faker('random_element', elements=['app_start_speed', 'sync_efficiency', 'battery_efficiency', 'storage_efficiency'])
    requirement_level = factory.Faker('random_element', elements=['must'])
    description = factory.Faker('paragraph')
    created_at = factory.Faker('date_time')
    updated_at = factory.Faker('date_time')


class AiAssistantFactory(factory.Factory):
    """Factory for ai_assistant entity."""

    class Meta:
        model = dict  # Replace with ORM model

    ai_assistant_id = factory.LazyFunction(uuid4)
    name = factory.Faker('name')
    provider = factory.Faker('text', max_nb_chars=50)
    is_enabled = factory.Faker('boolean')
    created_at = factory.Faker('date_time')
    updated_at = factory.Faker('date_time')


class SmartReplyFactory(factory.Factory):
    """Factory for smart_reply entity."""

    class Meta:
        model = dict  # Replace with ORM model

    smart_reply_id = factory.LazyFunction(uuid4)
    ai_assistant_id = factory.SubFactory(AiAssistantFactory)
    language_code = factory.Faker('language_code')
    reply_text = factory.Faker('paragraph')
    context_key = factory.Faker('text', max_nb_chars=50)
    created_at = factory.Faker('date_time')
    updated_at = factory.Faker('date_time')


class LocaleFactory(factory.Factory):
    """Factory for locale entity."""

    class Meta:
        model = dict  # Replace with ORM model

    locale_id = factory.LazyFunction(uuid4)
    locale_code = factory.Faker('locale')
    rtl_supported = factory.Faker('boolean')
    regional_date_format = factory.Faker('text', max_nb_chars=50)
    regional_number_format = factory.Faker('text', max_nb_chars=50)
    created_at = factory.Faker('date_time')
    updated_at = factory.Faker('date_time')


class StickerPackFactory(factory.Factory):
    """Factory for sticker_pack entity."""

    class Meta:
        model = dict  # Replace with ORM model

    sticker_pack_id = factory.LazyFunction(uuid4)
    locale_id = factory.SubFactory(LocaleFactory)
    name = factory.Faker('name')
    description = factory.Faker('paragraph')
    is_active = factory.Faker('boolean')
    created_at = factory.Faker('date_time')
    updated_at = factory.Faker('date_time')


class StickerSuggestionFactory(factory.Factory):
    """Factory for sticker_suggestion entity."""

    class Meta:
        model = dict  # Replace with ORM model

    sticker_suggestion_id = factory.LazyFunction(uuid4)
    sticker_pack_id = factory.SubFactory(StickerPackFactory)
    locale_id = factory.SubFactory(LocaleFactory)
    context_keyword = factory.Faker('text', max_nb_chars=50)
    confidence_score = factory.Faker('pydecimal', left_digits=5, right_digits=2, positive=True)
    created_at = factory.Faker('date_time')
    updated_at = factory.Faker('date_time')

