/**
 * Test data factories for all entities.
 *
 * Auto-generated by requirements_engineer pipeline.
 * Uses @faker-js/faker for realistic test data.
 */
import { faker } from '@faker-js/faker';

export interface User {
  userId: string;
  phoneNumber: string;
  phoneVerifiedAt: Date;
  status: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface UserProfile {
  profileId: string;
  userId: string;
  displayName: string;
  statusText: string;
  profileImageUrl: string;
  showPhoneNumber: boolean;
  qrCodeValue: string;
  qrCodeGeneratedAt: Date;
  createdAt: Date;
  updatedAt: Date;
}

export interface UserDevice {
  deviceId: string;
  userId: string;
  deviceName: string;
  devicePlatform: string;
  lastActiveAt: Date;
  createdAt: Date;
  updatedAt: Date;
}

export interface AuthCredential {
  credentialId: string;
  userId: string;
  credentialType: string;
  credentialData: string;
  isEnabled: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export interface Chat {
  chatId: string;
  chatName: string;
  isLocked: boolean;
  lockMethod: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface Message {
  messageId: string;
  chatId: string;
  senderUserId: string;
  messageType: string;
  contentText: string;
  parentMessageId: string;
  isForwarded: boolean;
  isDeleted: boolean;
  isEdited: boolean;
  editedAt: Date;
  expiresAt: Date;
  createdAt: Date;
  updatedAt: Date;
}

export interface MessageMedia {
  mediaId: string;
  messageId: string;
  mediaType: string;
  mediaUrl: string;
  isViewOnce: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export interface MessageReaction {
  reactionId: string;
  messageId: string;
  reactingUserId: string;
  emoji: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface GroupChat {
  groupChatId: string;
  groupName: string;
  groupDescription: string;
  inviteLinkUrl: string;
  inviteLinkEnabled: boolean;
  settingAdminOnlyPosting: boolean;
  settingAllowMemberInvite: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export interface GroupMember {
  groupMemberId: string;
  groupChatId: string;
  userId: string;
  role: string;
  leftSilently: boolean;
  leftAt: Date;
  createdAt: Date;
  updatedAt: Date;
}

export interface MessageMention {
  mentionId: string;
  messageId: string;
  mentionedUserId: string;
  positionStart: number;
  positionEnd: number;
  createdAt: Date;
  updatedAt: Date;
}

export interface Community {
  communityId: string;
  name: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface Group {
  groupId: string;
  communityId: string;
  name: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface Channel {
  channelId: string;
  groupId: string;
  name: string;
  isOneWayBroadcast: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export interface Poll {
  pollId: string;
  chatContextType: string;
  chatContextId: string;
  questionText: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface Call {
  callId: string;
  callType: string;
  isGroupCall: boolean;
  isEncrypted: boolean;
  screenShareEnabled: boolean;
  scheduledAt: Date;
  callLinkUrl: string;
  quickRejectMessage: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface Contact {
  contactId: string;
  displayName: string;
  phoneNumber: string;
  statusMuted: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export interface CallLog {
  callLogId: string;
  contactId: string;
  startedAt: Date;
  endedAt: Date;
  durationSeconds: number;
  createdAt: Date;
  updatedAt: Date;
}

export interface StatusUpdate {
  statusUpdateId: string;
  contactId: string;
  contentText: string;
  expiresAt: Date;
  visibility: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface StatusReply {
  statusReplyId: string;
  statusUpdateId: string;
  replyText: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface MediaItem {
  mediaItemId: string;
  senderContactId: string;
  statusUpdateId: string;
  mediaType: string;
  fileName: string;
  fileUrl: string;
  sizeBytes: number;
  editedFlag: boolean;
  editNotes: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface MediaAttachment {
  attachmentId: string;
  messageId: string;
  mediaType: string;
  fileUrl: string;
  sourceLibrary: string;
  isHd: boolean;
  durationSeconds: number;
  createdAt: Date;
  updatedAt: Date;
}

export interface EncryptionSession {
  encryptionSessionId: string;
  chatId: string;
  securityCode: string;
  verificationStatus: string;
  verifiedAt: Date;
  createdAt: Date;
  updatedAt: Date;
}

export interface ContactBlock {
  blockId: string;
  blockerUserId: string;
  blockedUserId: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface Report {
  reportId: string;
  reporterUserId: string;
  targetMessageId: string;
  targetUserId: string;
  reason: string;
  status: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface NotificationSetting {
  notificationSettingId: string;
  userId: string;
  pushEnabled: boolean;
  previewEnabled: boolean;
  quickReplyEnabled: boolean;
  doNotDisturbEnabled: boolean;
  reactionNotificationsEnabled: boolean;
  callNotificationMode: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface WhatsappUser {
  userId: string;
  phoneNumber: string;
  displayName: string;
  onlineStatusVisibility: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface Label {
  labelId: string;
  ownerUserId: string;
  labelName: string;
  color: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface Userprivacysetting {
  privacySettingId: string;
  userId: string;
  readReceiptEnabled: boolean;
  profilePhotoVisibility: string;
  statusTextVisibility: string;
  groupInvitePermission: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface Userappearancesetting {
  appearanceSettingId: string;
  userId: string;
  chatBackground: string;
  darkModeEnabled: boolean;
  languageCode: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface Userusagesetting {
  usageSettingId: string;
  userId: string;
  storageUsedMb: number;
  storageLimitMb: number;
  dataUsageControlEnabled: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export interface Userbackupsetting {
  backupSettingId: string;
  userId: string;
  cloudBackupEnabled: boolean;
  lastBackupAt: Date;
  createdAt: Date;
  updatedAt: Date;
}

export interface Backup {
  backupId: string;
  chatId: string;
  isEndToEndEncrypted: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export interface BusinessProfile {
  businessProfileId: string;
  displayName: string;
  verificationStatus: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface QuickReply {
  quickReplyId: string;
  businessProfileId: string;
  shortcut: string;
  messageText: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface AutoMessage {
  autoMessageId: string;
  businessProfileId: string;
  messageType: string;
  messageText: string;
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export interface Business {
  businessId: string;
  businessName: string;
  apiAccessEnabled: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export interface Product {
  productId: string;
  businessId: string;
  productName: string;
  description: string;
  priceAmount: number;
  currencyCode: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface Cart {
  cartId: string;
  businessId: string;
  status: string;
  totalAmount: number;
  currencyCode: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface Payment {
  paymentId: string;
  cartId: string;
  paymentStatus: string;
  amount: number;
  currencyCode: string;
  marketCode: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface BusinessStatistic {
  statId: string;
  businessId: string;
  periodStart: Date;
  periodEnd: Date;
  messagesSentCount: number;
  messagesReceivedCount: number;
  createdAt: Date;
  updatedAt: Date;
}

export interface IntegrationFeature {
  integrationFeatureId: string;
  featureType: string;
  requirementLevel: string;
  description: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface PerformanceRequirement {
  performanceRequirementId: string;
  metricType: string;
  requirementLevel: string;
  description: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface AiAssistant {
  aiAssistantId: string;
  name: string;
  provider: string;
  isEnabled: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export interface SmartReply {
  smartReplyId: string;
  aiAssistantId: string;
  languageCode: string;
  replyText: string;
  contextKey: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface Locale {
  localeId: string;
  localeCode: string;
  rtlSupported: boolean;
  regionalDateFormat: string;
  regionalNumberFormat: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface StickerPack {
  stickerPackId: string;
  localeId: string;
  name: string;
  description: string;
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export interface StickerSuggestion {
  stickerSuggestionId: string;
  stickerPackId: string;
  localeId: string;
  contextKeyword: string;
  confidenceScore: number;
  createdAt: Date;
  updatedAt: Date;
}


export function createUser(overrides: Partial<User> = {}): User {
  return {
    userId: faker.string.uuid(),
    phoneNumber: faker.phone.number(),
    phoneVerifiedAt: faker.date.recent(),
    status: faker.helpers.arrayElement(['active', 'inactive']),
    createdAt: faker.date.recent(),
    updatedAt: faker.date.recent(),
    ...overrides,
  };
}

export function createUserProfile(overrides: Partial<UserProfile> = {}): UserProfile {
  return {
    profileId: faker.string.uuid(),
    userId: createUser().id,
    displayName: faker.person.fullName(),
    statusText: faker.lorem.words(3),
    profileImageUrl: faker.lorem.words(3),
    showPhoneNumber: faker.datatype.boolean(),
    qrCodeValue: faker.lorem.words(3),
    qrCodeGeneratedAt: faker.date.recent(),
    createdAt: faker.date.recent(),
    updatedAt: faker.date.recent(),
    ...overrides,
  };
}

export function createUserDevice(overrides: Partial<UserDevice> = {}): UserDevice {
  return {
    deviceId: faker.string.uuid(),
    userId: createUser().id,
    deviceName: faker.lorem.words(3),
    devicePlatform: faker.helpers.arrayElement(['ios', 'android', 'web', 'desktop', 'other']),
    lastActiveAt: faker.date.recent(),
    createdAt: faker.date.recent(),
    updatedAt: faker.date.recent(),
    ...overrides,
  };
}

export function createAuthCredential(overrides: Partial<AuthCredential> = {}): AuthCredential {
  return {
    credentialId: faker.string.uuid(),
    userId: createUser().id,
    credentialType: faker.helpers.arrayElement(['pin_2fa', 'biometric', 'passkey']),
    credentialData: faker.lorem.paragraph(),
    isEnabled: faker.datatype.boolean(),
    createdAt: faker.date.recent(),
    updatedAt: faker.date.recent(),
    ...overrides,
  };
}

export function createChat(overrides: Partial<Chat> = {}): Chat {
  return {
    chatId: faker.string.uuid(),
    chatName: faker.lorem.words(3),
    isLocked: faker.datatype.boolean(),
    lockMethod: faker.helpers.arrayElement(['pin', 'biometric', 'password', 'none']),
    createdAt: faker.date.recent(),
    updatedAt: faker.date.recent(),
    ...overrides,
  };
}

export function createMessage(overrides: Partial<Message> = {}): Message {
  return {
    messageId: faker.string.uuid(),
    chatId: createChat().id,
    senderUserId: faker.lorem.words(3),
    messageType: faker.helpers.arrayElement(['text', 'voice', 'media']),
    contentText: faker.lorem.paragraph(),
    parentMessageId: createMessage().id,
    isForwarded: faker.datatype.boolean(),
    isDeleted: faker.datatype.boolean(),
    isEdited: faker.datatype.boolean(),
    editedAt: faker.date.recent(),
    expiresAt: faker.date.recent(),
    createdAt: faker.date.recent(),
    updatedAt: faker.date.recent(),
    ...overrides,
  };
}

export function createMessageMedia(overrides: Partial<MessageMedia> = {}): MessageMedia {
  return {
    mediaId: faker.string.uuid(),
    messageId: createMessage().id,
    mediaType: faker.helpers.arrayElement(['voice', 'image', 'video', 'file']),
    mediaUrl: faker.lorem.words(3),
    isViewOnce: faker.datatype.boolean(),
    createdAt: faker.date.recent(),
    updatedAt: faker.date.recent(),
    ...overrides,
  };
}

export function createMessageReaction(overrides: Partial<MessageReaction> = {}): MessageReaction {
  return {
    reactionId: faker.string.uuid(),
    messageId: createMessage().id,
    reactingUserId: faker.lorem.words(3),
    emoji: faker.lorem.words(3),
    createdAt: faker.date.recent(),
    updatedAt: faker.date.recent(),
    ...overrides,
  };
}

export function createGroupChat(overrides: Partial<GroupChat> = {}): GroupChat {
  return {
    groupChatId: faker.string.uuid(),
    groupName: faker.lorem.words(3),
    groupDescription: faker.lorem.paragraph(),
    inviteLinkUrl: faker.lorem.words(3),
    inviteLinkEnabled: faker.datatype.boolean(),
    settingAdminOnlyPosting: faker.datatype.boolean(),
    settingAllowMemberInvite: faker.datatype.boolean(),
    createdAt: faker.date.recent(),
    updatedAt: faker.date.recent(),
    ...overrides,
  };
}

export function createGroupMember(overrides: Partial<GroupMember> = {}): GroupMember {
  return {
    groupMemberId: faker.string.uuid(),
    groupChatId: createGroupchat().id,
    userId: createUser().id,
    role: faker.helpers.arrayElement(['admin', 'member']),
    leftSilently: faker.datatype.boolean(),
    leftAt: faker.date.recent(),
    createdAt: faker.date.recent(),
    updatedAt: faker.date.recent(),
    ...overrides,
  };
}

export function createMessageMention(overrides: Partial<MessageMention> = {}): MessageMention {
  return {
    mentionId: faker.string.uuid(),
    messageId: createMessage().id,
    mentionedUserId: createUser().id,
    positionStart: faker.number.int({ min: 0, max: 10000 }),
    positionEnd: faker.number.int({ min: 0, max: 10000 }),
    createdAt: faker.date.recent(),
    updatedAt: faker.date.recent(),
    ...overrides,
  };
}

export function createCommunity(overrides: Partial<Community> = {}): Community {
  return {
    communityId: faker.string.uuid(),
    name: faker.person.fullName(),
    createdAt: faker.date.recent(),
    updatedAt: faker.date.recent(),
    ...overrides,
  };
}

export function createGroup(overrides: Partial<Group> = {}): Group {
  return {
    groupId: faker.string.uuid(),
    communityId: createCommunity().id,
    name: faker.person.fullName(),
    createdAt: faker.date.recent(),
    updatedAt: faker.date.recent(),
    ...overrides,
  };
}

export function createChannel(overrides: Partial<Channel> = {}): Channel {
  return {
    channelId: faker.string.uuid(),
    groupId: createGroup().id,
    name: faker.person.fullName(),
    isOneWayBroadcast: faker.datatype.boolean(),
    createdAt: faker.date.recent(),
    updatedAt: faker.date.recent(),
    ...overrides,
  };
}

export function createPoll(overrides: Partial<Poll> = {}): Poll {
  return {
    pollId: faker.string.uuid(),
    chatContextType: faker.helpers.arrayElement(['group', 'individual']),
    chatContextId: faker.string.uuid(),
    questionText: faker.lorem.paragraph(),
    createdAt: faker.date.recent(),
    updatedAt: faker.date.recent(),
    ...overrides,
  };
}

export function createCall(overrides: Partial<Call> = {}): Call {
  return {
    callId: faker.string.uuid(),
    callType: faker.helpers.arrayElement(['voice', 'video']),
    isGroupCall: faker.datatype.boolean(),
    isEncrypted: faker.datatype.boolean(),
    screenShareEnabled: faker.datatype.boolean(),
    scheduledAt: faker.date.recent(),
    callLinkUrl: faker.lorem.words(3),
    quickRejectMessage: faker.lorem.words(3),
    createdAt: faker.date.recent(),
    updatedAt: faker.date.recent(),
    ...overrides,
  };
}

export function createContact(overrides: Partial<Contact> = {}): Contact {
  return {
    contactId: faker.string.uuid(),
    displayName: faker.person.fullName(),
    phoneNumber: faker.phone.number(),
    statusMuted: faker.datatype.boolean(),
    createdAt: faker.date.recent(),
    updatedAt: faker.date.recent(),
    ...overrides,
  };
}

export function createCallLog(overrides: Partial<CallLog> = {}): CallLog {
  return {
    callLogId: faker.string.uuid(),
    contactId: createContact().id,
    startedAt: faker.date.recent(),
    endedAt: faker.date.recent(),
    durationSeconds: faker.number.int({ min: 0, max: 10000 }),
    createdAt: faker.date.recent(),
    updatedAt: faker.date.recent(),
    ...overrides,
  };
}

export function createStatusUpdate(overrides: Partial<StatusUpdate> = {}): StatusUpdate {
  return {
    statusUpdateId: faker.string.uuid(),
    contactId: createContact().id,
    contentText: faker.lorem.paragraph(),
    expiresAt: faker.date.recent(),
    visibility: faker.helpers.arrayElement(['public', 'contacts_only', 'custom']),
    createdAt: faker.date.recent(),
    updatedAt: faker.date.recent(),
    ...overrides,
  };
}

export function createStatusReply(overrides: Partial<StatusReply> = {}): StatusReply {
  return {
    statusReplyId: faker.string.uuid(),
    statusUpdateId: createStatusupdate().id,
    replyText: faker.lorem.paragraph(),
    createdAt: faker.date.recent(),
    updatedAt: faker.date.recent(),
    ...overrides,
  };
}

export function createMediaItem(overrides: Partial<MediaItem> = {}): MediaItem {
  return {
    mediaItemId: faker.string.uuid(),
    senderContactId: createContact().id,
    statusUpdateId: createStatusupdate().id,
    mediaType: faker.helpers.arrayElement(['image', 'video', 'document']),
    fileName: faker.lorem.words(3),
    fileUrl: faker.lorem.words(3),
    sizeBytes: faker.number.int({ min: 0, max: 10000 }),
    editedFlag: faker.datatype.boolean(),
    editNotes: faker.lorem.paragraph(),
    createdAt: faker.date.recent(),
    updatedAt: faker.date.recent(),
    ...overrides,
  };
}

export function createMediaAttachment(overrides: Partial<MediaAttachment> = {}): MediaAttachment {
  return {
    attachmentId: faker.string.uuid(),
    messageId: createMessage().id,
    mediaType: faker.helpers.arrayElement(['sticker', 'gif', 'audio', 'image', 'video']),
    fileUrl: faker.lorem.words(3),
    sourceLibrary: faker.helpers.arrayElement(['camera', 'gallery', 'external']),
    isHd: faker.datatype.boolean(),
    durationSeconds: faker.number.int({ min: 0, max: 10000 }),
    createdAt: faker.date.recent(),
    updatedAt: faker.date.recent(),
    ...overrides,
  };
}

export function createEncryptionSession(overrides: Partial<EncryptionSession> = {}): EncryptionSession {
  return {
    encryptionSessionId: faker.string.uuid(),
    chatId: faker.string.uuid(),
    securityCode: faker.lorem.words(3),
    verificationStatus: faker.helpers.arrayElement(['unverified', 'verified']),
    verifiedAt: faker.date.recent(),
    createdAt: faker.date.recent(),
    updatedAt: faker.date.recent(),
    ...overrides,
  };
}

export function createContactBlock(overrides: Partial<ContactBlock> = {}): ContactBlock {
  return {
    blockId: faker.string.uuid(),
    blockerUserId: createUser().id,
    blockedUserId: createUser().id,
    createdAt: faker.date.recent(),
    updatedAt: faker.date.recent(),
    ...overrides,
  };
}

export function createReport(overrides: Partial<Report> = {}): Report {
  return {
    reportId: faker.string.uuid(),
    reporterUserId: createUser().id,
    targetMessageId: createMessage().id,
    targetUserId: createUser().id,
    reason: faker.lorem.paragraph(),
    status: faker.helpers.arrayElement(['active', 'inactive']),
    createdAt: faker.date.recent(),
    updatedAt: faker.date.recent(),
    ...overrides,
  };
}

export function createNotificationSetting(overrides: Partial<NotificationSetting> = {}): NotificationSetting {
  return {
    notificationSettingId: faker.string.uuid(),
    userId: createUser().id,
    pushEnabled: faker.datatype.boolean(),
    previewEnabled: faker.datatype.boolean(),
    quickReplyEnabled: faker.datatype.boolean(),
    doNotDisturbEnabled: faker.datatype.boolean(),
    reactionNotificationsEnabled: faker.datatype.boolean(),
    callNotificationMode: faker.helpers.arrayElement(['all', 'missed_only', 'none']),
    createdAt: faker.date.recent(),
    updatedAt: faker.date.recent(),
    ...overrides,
  };
}

export function createWhatsappUser(overrides: Partial<WhatsappUser> = {}): WhatsappUser {
  return {
    userId: faker.string.uuid(),
    phoneNumber: faker.phone.number(),
    displayName: faker.person.fullName(),
    onlineStatusVisibility: faker.helpers.arrayElement(['public', 'contacts_only', 'nobody']),
    createdAt: faker.date.recent(),
    updatedAt: faker.date.recent(),
    ...overrides,
  };
}

export function createLabel(overrides: Partial<Label> = {}): Label {
  return {
    labelId: faker.string.uuid(),
    ownerUserId: createWhatsappuser().id,
    labelName: faker.lorem.words(3),
    color: faker.color.rgb(),
    createdAt: faker.date.recent(),
    updatedAt: faker.date.recent(),
    ...overrides,
  };
}

export function createUserprivacysetting(overrides: Partial<Userprivacysetting> = {}): Userprivacysetting {
  return {
    privacySettingId: faker.string.uuid(),
    userId: createUser().id,
    readReceiptEnabled: faker.datatype.boolean(),
    profilePhotoVisibility: faker.helpers.arrayElement(['everyone', 'contacts', 'nobody']),
    statusTextVisibility: faker.helpers.arrayElement(['everyone', 'contacts', 'nobody']),
    groupInvitePermission: faker.helpers.arrayElement(['everyone', 'contacts', 'nobody']),
    createdAt: faker.date.recent(),
    updatedAt: faker.date.recent(),
    ...overrides,
  };
}

export function createUserappearancesetting(overrides: Partial<Userappearancesetting> = {}): Userappearancesetting {
  return {
    appearanceSettingId: faker.string.uuid(),
    userId: createUser().id,
    chatBackground: faker.lorem.words(3),
    darkModeEnabled: faker.datatype.boolean(),
    languageCode: faker.lorem.words(3),
    createdAt: faker.date.recent(),
    updatedAt: faker.date.recent(),
    ...overrides,
  };
}

export function createUserusagesetting(overrides: Partial<Userusagesetting> = {}): Userusagesetting {
  return {
    usageSettingId: faker.string.uuid(),
    userId: createUser().id,
    storageUsedMb: parseFloat(faker.finance.amount()),
    storageLimitMb: parseFloat(faker.finance.amount()),
    dataUsageControlEnabled: faker.datatype.boolean(),
    createdAt: faker.date.recent(),
    updatedAt: faker.date.recent(),
    ...overrides,
  };
}

export function createUserbackupsetting(overrides: Partial<Userbackupsetting> = {}): Userbackupsetting {
  return {
    backupSettingId: faker.string.uuid(),
    userId: createUser().id,
    cloudBackupEnabled: faker.datatype.boolean(),
    lastBackupAt: faker.date.recent(),
    createdAt: faker.date.recent(),
    updatedAt: faker.date.recent(),
    ...overrides,
  };
}

export function createBackup(overrides: Partial<Backup> = {}): Backup {
  return {
    backupId: faker.string.uuid(),
    chatId: createChat().id,
    isEndToEndEncrypted: faker.datatype.boolean(),
    createdAt: faker.date.recent(),
    updatedAt: faker.date.recent(),
    ...overrides,
  };
}

export function createBusinessProfile(overrides: Partial<BusinessProfile> = {}): BusinessProfile {
  return {
    businessProfileId: faker.string.uuid(),
    displayName: faker.person.fullName(),
    verificationStatus: faker.helpers.arrayElement(['unverified', 'pending', 'verified']),
    createdAt: faker.date.recent(),
    updatedAt: faker.date.recent(),
    ...overrides,
  };
}

export function createQuickReply(overrides: Partial<QuickReply> = {}): QuickReply {
  return {
    quickReplyId: faker.string.uuid(),
    businessProfileId: createBusinessprofile().id,
    shortcut: faker.lorem.words(3),
    messageText: faker.lorem.paragraph(),
    createdAt: faker.date.recent(),
    updatedAt: faker.date.recent(),
    ...overrides,
  };
}

export function createAutoMessage(overrides: Partial<AutoMessage> = {}): AutoMessage {
  return {
    autoMessageId: faker.string.uuid(),
    businessProfileId: createBusinessprofile().id,
    messageType: faker.helpers.arrayElement(['away', 'greeting']),
    messageText: faker.lorem.paragraph(),
    isActive: faker.datatype.boolean(),
    createdAt: faker.date.recent(),
    updatedAt: faker.date.recent(),
    ...overrides,
  };
}

export function createBusiness(overrides: Partial<Business> = {}): Business {
  return {
    businessId: faker.string.uuid(),
    businessName: faker.lorem.words(3),
    apiAccessEnabled: faker.datatype.boolean(),
    createdAt: faker.date.recent(),
    updatedAt: faker.date.recent(),
    ...overrides,
  };
}

export function createProduct(overrides: Partial<Product> = {}): Product {
  return {
    productId: faker.string.uuid(),
    businessId: createBusiness().id,
    productName: faker.lorem.words(3),
    description: faker.lorem.paragraph(),
    priceAmount: parseFloat(faker.finance.amount()),
    currencyCode: faker.lorem.words(3),
    createdAt: faker.date.recent(),
    updatedAt: faker.date.recent(),
    ...overrides,
  };
}

export function createCart(overrides: Partial<Cart> = {}): Cart {
  return {
    cartId: faker.string.uuid(),
    businessId: createBusiness().id,
    status: faker.helpers.arrayElement(['active', 'inactive']),
    totalAmount: parseFloat(faker.finance.amount()),
    currencyCode: faker.lorem.words(3),
    createdAt: faker.date.recent(),
    updatedAt: faker.date.recent(),
    ...overrides,
  };
}

export function createPayment(overrides: Partial<Payment> = {}): Payment {
  return {
    paymentId: faker.string.uuid(),
    cartId: createCart().id,
    paymentStatus: faker.helpers.arrayElement(['pending', 'completed', 'failed', 'refunded']),
    amount: parseFloat(faker.finance.amount()),
    currencyCode: faker.lorem.words(3),
    marketCode: faker.lorem.words(3),
    createdAt: faker.date.recent(),
    updatedAt: faker.date.recent(),
    ...overrides,
  };
}

export function createBusinessStatistic(overrides: Partial<BusinessStatistic> = {}): BusinessStatistic {
  return {
    statId: faker.string.uuid(),
    businessId: createBusiness().id,
    periodStart: faker.date.recent(),
    periodEnd: faker.date.recent(),
    messagesSentCount: faker.number.int({ min: 0, max: 10000 }),
    messagesReceivedCount: faker.number.int({ min: 0, max: 10000 }),
    createdAt: faker.date.recent(),
    updatedAt: faker.date.recent(),
    ...overrides,
  };
}

export function createIntegrationFeature(overrides: Partial<IntegrationFeature> = {}): IntegrationFeature {
  return {
    integrationFeatureId: faker.string.uuid(),
    featureType: faker.helpers.arrayElement(['share_extension', 'voice_assistant', 'widget', 'watch_app', 'desktop_app', 'web_version']),
    requirementLevel: faker.helpers.arrayElement(['must', 'should']),
    description: faker.lorem.paragraph(),
    createdAt: faker.date.recent(),
    updatedAt: faker.date.recent(),
    ...overrides,
  };
}

export function createPerformanceRequirement(overrides: Partial<PerformanceRequirement> = {}): PerformanceRequirement {
  return {
    performanceRequirementId: faker.string.uuid(),
    metricType: faker.helpers.arrayElement(['app_start_speed', 'sync_efficiency', 'battery_efficiency', 'storage_efficiency']),
    requirementLevel: faker.helpers.arrayElement(['must']),
    description: faker.lorem.paragraph(),
    createdAt: faker.date.recent(),
    updatedAt: faker.date.recent(),
    ...overrides,
  };
}

export function createAiAssistant(overrides: Partial<AiAssistant> = {}): AiAssistant {
  return {
    aiAssistantId: faker.string.uuid(),
    name: faker.person.fullName(),
    provider: faker.lorem.words(3),
    isEnabled: faker.datatype.boolean(),
    createdAt: faker.date.recent(),
    updatedAt: faker.date.recent(),
    ...overrides,
  };
}

export function createSmartReply(overrides: Partial<SmartReply> = {}): SmartReply {
  return {
    smartReplyId: faker.string.uuid(),
    aiAssistantId: createAiassistant().id,
    languageCode: faker.lorem.words(3),
    replyText: faker.lorem.paragraph(),
    contextKey: faker.lorem.words(3),
    createdAt: faker.date.recent(),
    updatedAt: faker.date.recent(),
    ...overrides,
  };
}

export function createLocale(overrides: Partial<Locale> = {}): Locale {
  return {
    localeId: faker.string.uuid(),
    localeCode: faker.lorem.words(3),
    rtlSupported: faker.datatype.boolean(),
    regionalDateFormat: faker.lorem.words(3),
    regionalNumberFormat: faker.lorem.words(3),
    createdAt: faker.date.recent(),
    updatedAt: faker.date.recent(),
    ...overrides,
  };
}

export function createStickerPack(overrides: Partial<StickerPack> = {}): StickerPack {
  return {
    stickerPackId: faker.string.uuid(),
    localeId: createLocale().id,
    name: faker.person.fullName(),
    description: faker.lorem.paragraph(),
    isActive: faker.datatype.boolean(),
    createdAt: faker.date.recent(),
    updatedAt: faker.date.recent(),
    ...overrides,
  };
}

export function createStickerSuggestion(overrides: Partial<StickerSuggestion> = {}): StickerSuggestion {
  return {
    stickerSuggestionId: faker.string.uuid(),
    stickerPackId: createStickerpack().id,
    localeId: createLocale().id,
    contextKeyword: faker.lorem.words(3),
    confidenceScore: parseFloat(faker.finance.amount()),
    createdAt: faker.date.recent(),
    updatedAt: faker.date.recent(),
    ...overrides,
  };
}

export function createBatch<T>(factory: (o?: Partial<T>) => T, count: number): T[] {
  return Array.from({ length: count }, () => factory());
}
